### ISSUE TITLE
There’s already 2 FloatingText plugins. Odds are it won’t get accepted.

### ISSUE THREAD

**Issue by WavyCraftNetwork** [AstroKotlin/AFloatingText#2]
As the title explains I don’t think they will approve it since it doesn’t have enough features.

**Comment by AstroKotlin** [comment]
I think I will add more features in the future if it is approved

**Comment by WavyCraftNetwork** [comment]
Told you so.

**Comment by AstroKotlin** [comment]
No problem, I'm just doing it for fun
